### 1 단일 알림 생성
POST http://localhost:8080/v1/notifications
Content-Type: application/json

{
  "subscriberId": 2,
  "notificationType": "CANCELLATION_PROCESSED",
  "metadata": {
    "courseName": "<테스트 알림>"
  }
}

### 1-2 단일 알림 생성 (Push Event)
POST http://localhost:8080/v1/notifications
Content-Type: application/json

{
  "subscriberId": 1,
  "notificationType": "PAYMENT_CONFIRMED",
  "metadata": {
    "orderId": "3"
  }
}

### 2. 알림 상태 조회
GET http://localhost:8080/v1/notifications/1/status

### 3. 구독자 알림 목록 조회
GET http://localhost:8080/v1/notifications/subscribers/1?page=0&size=20

### 4. 알림 상세 정보 조회
GET http://localhost:8080/v1/notifications/1

### 5. 알림 읽음 처리 (App)
PATCH http://localhost:8080/v1/notifications/1/read

### 6. 알림 읽음 처리 (Email - 리다이렉트)
GET http://localhost:8080/v1/notifications/2/read

### 7. 실패 알림 재시도
POST http://localhost:8080/v1/notifications/retry

### 8. 대량(Public) 알림 생성
POST http://localhost:8080/v1/notifications/public
Content-Type: application/json

{
  "type": "NEW_LECTURE_OPENED",
  "metadata": {
    "courseName": "신규 특강"
  }
}

### 9. 대량(Public) 알림 읽음 처리 (App)
PATCH http://localhost:8080/v1/notifications/public/1/read?subscriberId=1

### 9-1. 대량(Public) 알림 읽음 처리 (Email - 리다이렉트)
GET http://localhost:8080/v1/notifications/public/1/read?subscriberId=1

### 10. 알림 예약 생성
POST http://localhost:8080/v1/reservations
Content-Type: application/json

{
  "subscriberIds": [1, 2, 3],
  "type": "NEW_LECTURE_OPENED",
  "reservationTime": "2026-05-28T10:00:00"
}

### 11. 메시지 템플릿 생성 (Admin)
POST http://localhost:8080/v1/admin/templates
Content-Type: application/json

{
  "channel": "IN_APP",
  "type": "PAYMENT_CONFIRMED",
  "content": "결제가 완료되었습니다. 주문 번호: {orderId}"
}

### 12. 메시지 템플릿 수정 (Admin)
PUT http://localhost:8080/v1/admin/templates/1
Content-Type: application/json

{
  "content": "결제가 정상적으로 처리되었습니다. 주문 번호: {orderId}"
}

### 13. 메시지 템플릿 전체 조회 (Admin)
GET http://localhost:8080/v1/admin/templates

### 14. 특정 메시지 템플릿 상세 조회 (Admin)
GET http://localhost:8080/v1/admin/templates/1

### 15. 메시지 템플릿 변경 이력 조회 (Admin)
GET http://localhost:8080/v1/admin/templates/1/histories
