spring:
  application:
    name: Notifier

  profiles:
    active: local

  config:
    import:
      - logging.yml
      - db.yml

---
spring:
  config:
    activate:
      on-profile: local


---
spring:
  config:
    activate:
      on-profile: dev



---
spring:
  config:
    activate:
      on-profile: prod