spring:
  application:
    name: Notifier

  profiles:
    active: local

  config:
    import:
      - classpath:logging.yml
      - classpath:db.yml
      - classpath:rdb-retry.yml
      - classpath:scheduler.yml

  threads:
    virtual:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: local


---
spring:
  config:
    activate:
      on-profile: dev


