spring:
  application:
    name: Notifier

  profiles:
    active: local

  config:
    import:
      - logging.yml
      - db.yml
      - rdb-retry.yml
      - scheduler.yml

  threads:
    virtual:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: local


---
spring:
  config:
    activate:
      on-profile: dev


