
    create table if not exists message_template_histories (
        created_at timestamp(6),
        id bigint generated by default as identity,
        template_id bigint not null,
        content text not null,
        primary key (id)
    );

    create table if not exists message_templates (
        is_active boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        version bigint,
        content text not null,
        channel enum ('EMAIL','IN_APP') not null,
        notification_type enum ('CANCELLATION_PROCESSED','COUPON_EXPIRY_REMINDER','COUPON_ISSUED','COURSE_START_REMINDER','NEW_LECTURE_OPENED','PAYMENT_CONFIRMED') not null,
        primary key (id),
        constraint uk_msg_tpl_channel_type unique (channel, notification_type)
    );

    create table if not exists mock_user_channel_settings (
        is_active boolean not null,
        mock_user_id bigint not null,
        channel_settings_key enum ('EMAIL','IN_APP') not null,
        primary key (mock_user_id, channel_settings_key)
    );

    create table if not exists mock_user_notification_settings (
        is_subscribed boolean not null,
        mock_user_id bigint not null,
        notification_settings_key enum ('CANCELLATION_PROCESSED','COUPON_EXPIRY_REMINDER','COUPON_ISSUED','COURSE_START_REMINDER','NEW_LECTURE_OPENED','PAYMENT_CONFIRMED') not null,
        primary key (mock_user_id, notification_settings_key)
    );

    create table if not exists mock_users (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        version bigint,
        primary key (id)
    );

    create table if not exists notification_event_logs (
        published boolean not null,
        retry_count integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        published_at timestamp(6),
        reference_id bigint not null,
        subscriber_id bigint,
        updated_at timestamp(6),
        version bigint,
        fail_reason varchar(255),
        metadata TEXT,
        channel_type enum ('EMAIL','IN_APP') not null,
        event_status enum ('FAILED','PROCESSING','REQUESTED','RETRIED','SENT') not null,
        notification_type enum ('CANCELLATION_PROCESSED','COUPON_EXPIRY_REMINDER','COUPON_ISSUED','COURSE_START_REMINDER','NEW_LECTURE_OPENED','PAYMENT_CONFIRMED') not null,
        reference_type enum ('PERSONAL','PUBLIC') not null,
        primary key (id),
        constraint uk_notification_event_logs_duplicate unique (reference_id, reference_type, channel_type, subscriber_id, event_status, retry_count)
    );

    create table if not exists notifications (
        is_read boolean not null,
        manual_retry_count integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        subscriber_id bigint not null,
        updated_at timestamp(6),
        version bigint,
        metadata varchar(2000),
        idempotency_key varchar(255),
        message varchar(255),
        channel enum ('EMAIL','IN_APP') not null,
        notification_type enum ('CANCELLATION_PROCESSED','COUPON_EXPIRY_REMINDER','COUPON_ISSUED','COURSE_START_REMINDER','NEW_LECTURE_OPENED','PAYMENT_CONFIRMED') not null,
        status enum ('COMPLETED','FAILED','PENDING','RETRYING') not null,
        primary key (id),
        constraint uk_notification_idempotency unique (subscriber_id, notification_type, channel, idempotency_key)
    );

    create table if not exists public_notification_dlq (
        created_at timestamp(6),
        id bigint generated by default as identity,
        error_message varchar(2000),
        event_payload TEXT,
        status enum ('PENDING','RESOLVED') not null,
        primary key (id)
    );

    create table if not exists public_notification_receipts (
        created_at timestamp(6),
        id bigint generated by default as identity,
        public_notification_id bigint not null,
        subscriber_id bigint not null,
        updated_at timestamp(6),
        version bigint,
        primary key (id),
        constraint uk_public_notification_receipt_duplicate unique (subscriber_id, public_notification_id)
    );

    create table if not exists public_notifications (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        version bigint,
        metadata varchar(2000),
        idempotency_key varchar(255) not null unique,
        notification_type enum ('CANCELLATION_PROCESSED','COUPON_EXPIRY_REMINDER','COUPON_ISSUED','COURSE_START_REMINDER','NEW_LECTURE_OPENED','PAYMENT_CONFIRMED') not null,
        status enum ('COMPLETED','FAILED','PENDING','RETRYING') not null,
        primary key (id)
    );

    create table if not exists reservation_notifications (
        is_published boolean not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        reservation_time timestamp(6) not null,
        metadata TEXT,
        updated_at timestamp(6),
        version bigint,
        notification_type enum ('CANCELLATION_PROCESSED','COUPON_EXPIRY_REMINDER','COUPON_ISSUED','COURSE_START_REMINDER','NEW_LECTURE_OPENED','PAYMENT_CONFIRMED') not null,
        primary key (id)
    );

    create table if not exists shedlock (
        lock_until timestamp(6) not null,
        locked_at timestamp(6) not null,
        name varchar(64) not null,
        locked_by varchar(255) not null,
        primary key (name)
    );

    alter table if exists mock_user_channel_settings 
       add constraint IF NOT EXISTS FKhoi1tl6laji1vxoaisstc2bl7 
       foreign key (mock_user_id) 
       references mock_users;

    alter table if exists mock_user_notification_settings 
       add constraint IF NOT EXISTS FKei4tdv1are7g4kxkcjfrl1kw6 
       foreign key (mock_user_id) 
       references mock_users;
