package io.github.choizz.notifier.core.domain.model;

public enum NotificationType {
	ENROLLMENT_COMPLETED,
	PAYMENT_CONFIRMED,
	COURSE_START_REMINDER,
	CANCELLATION_PROCESSED,
	NEW_LECTURE_OPENED,
	COUPON_ISSUED,
	WISHLIST_COURSE_DISCOUNT,
	COUPON_EXPIRY_REMINDER
}
